import { SipdRealizationRecord } from './types';

export const MOCK_SIPD_REALIZATION_DATA: SipdRealizationRecord[] = [
  {
    idDaerah: "5207",
    tahun: "2026",
    kodeUrusan: "1",
    namaUrusan: "URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR",
    kodeBidangUrusan: "1.01",
    namaBidangUrusan: "PENDIDIKAN",
    kodeFungsi: "05",
    namaFungsi: "Pendidikan",
    kodeSubFungsi: "01",
    namaSubFungsi: "Pendidikan Dasar",
    kodeSkpd: "1.01.0.00.0.00.01.0000",
    namaSkpd: "Dinas Pendidikan dan Kebudayaan",
    kodeSubSkpd: "1.01.0.00.0.00.01.0001",
    namaSubSkpd: "Sekretariat Dinas Pendidikan dan Kebudayaan",
    kodeProgram: "1.01.01",
    namaProgram: "PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH KABUPATEN/KOTA",
    kodeKegiatan: "1.01.01.2.01",
    namaKegiatan: "Penyediaan Gaji dan Tunjangan ASN",
    kodeSubKegiatan: "1.01.01.2.01.01",
    namaSubKegiatan: "Penyediaan Gaji dan Tunjangan ASN - Guru",
    kodeRekening: "5.1.01.01",
    namaRekening: "Belanja Gaji Pokok PNS/CPNS",
    alokasiAnggaran: 18500200000,
    realisasiAnggaran: 7420100000
  },
  {
    idDaerah: "5207",
    tahun: "2026",
    kodeUrusan: "1",
    namaUrusan: "URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR",
    kodeBidangUrusan: "1.01",
    namaBidangUrusan: "PENDIDIKAN",
    kodeFungsi: "05",
    namaFungsi: "Pendidikan",
    kodeSubFungsi: "01",
    namaSubFungsi: "Pendidikan Dasar",
    kodeSkpd: "1.01.0.00.0.00.01.0000",
    namaSkpd: "Dinas Pendidikan dan Kebudayaan",
    kodeSubSkpd: "1.01.0.00.0.00.01.0002",
    namaSubSkpd: "Bidang Pembinaan Sekolah Dasar (SD)",
    kodeProgram: "1.01.02",
    namaProgram: "PROGRAM PENGELOLAAN PENDIDIKAN",
    kodeKegiatan: "1.01.02.2.01",
    namaKegiatan: "Pengelolaan Pendidikan Sekolah Dasar",
    kodeSubKegiatan: "1.01.02.2.01.03",
    namaSubKegiatan: "Pemberian Bantuan Operasional Sekolah (BOS) SD Daerah",
    kodeRekening: "5.1.02.02",
    namaRekening: "Belanja Barang dan Jasa - BOS Daerah SD",
    alokasiAnggaran: 12400000000,
    realisasiAnggaran: 6200000000
  },
  {
    idDaerah: "5207",
    tahun: "2026",
    kodeUrusan: "1",
    namaUrusan: "URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR",
    kodeBidangUrusan: "1.02",
    namaBidangUrusan: "KESEHATAN",
    kodeFungsi: "07",
    namaFungsi: "Kesehatan",
    kodeSubFungsi: "02",
    namaSubFungsi: "Upaya Kesehatan",
    kodeSkpd: "1.02.0.00.0.00.01.0000",
    namaSkpd: "Dinas Kesehatan",
    kodeSubSkpd: "1.02.0.00.0.00.01.0001",
    namaSubSkpd: "Puskesmas Taliwang",
    kodeProgram: "1.02.02",
    namaProgram: "PROGRAM PEMENUHAN UPAYA KESEHATAN PERORANGAN DAN UPAYA KESEHATAN MASYARAKAT",
    kodeKegiatan: "1.02.02.2.02",
    namaKegiatan: "Penyediaan Layanan Kesehatan untuk UKP Rujukan",
    kodeSubKegiatan: "1.02.02.2.02.12",
    namaSubKegiatan: "Penyediaan Obat, Vaksin, dan Bahan Medis Habis Pakai",
    kodeRekening: "5.1.02.01",
    namaRekening: "Belanja BMHP (Bahan Medis Habis Pakai) Puskesmas",
    alokasiAnggaran: 8900000000,
    realisasiAnggaran: 4895000000
  },
  {
    idDaerah: "5207",
    tahun: "2026",
    kodeUrusan: "1",
    namaUrusan: "URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR",
    kodeBidangUrusan: "1.03",
    namaBidangUrusan: "PEKERJAAN UMUM DAN PENATAAN RUANG",
    kodeFungsi: "06",
    namaFungsi: "Perumahan dan Fasilitas Umum",
    kodeSubFungsi: "03",
    namaSubFungsi: "Sanitasi dan Air Bersih",
    kodeSkpd: "1.03.0.00.0.00.01.0000",
    namaSkpd: "Dinas Pekerjaan Umum, Penataan Ruang, Perumahan dan Permukiman",
    kodeSubSkpd: "1.03.0.00.0.00.01.0003",
    namaSubSkpd: "Bidang Cipta Karya",
    kodeProgram: "1.03.02",
    namaProgram: "PROGRAM PENGEMBANGAN SISTEM DAN PENGELOLAAN PERSAMPAHAN SERTA AIR LIMBA",
    kodeKegiatan: "1.03.02.2.01",
    namaKegiatan: "Penyambungan Jaringan Distribusi Air Bersih Pedesaan",
    kodeSubKegiatan: "1.03.02.2.01.02",
    namaSubKegiatan: "Pembangunan dan Rehabilitasi Sarana Air Bersih",
    kodeRekening: "5.2.04.01",
    namaRekening: "Belanja Modal Jaringan Irigasi dan Sanitasi",
    alokasiAnggaran: 15600000000,
    realisasiAnggaran: 3120000000
  },
  {
    idDaerah: "5207",
    tahun: "2026",
    kodeUrusan: "2",
    namaUrusan: "URUSAN PEMERINTAHAN WAJIB YANG TIDAK BERKAITAN DENGAN PELAYANAN DASAR",
    kodeBidangUrusan: "2.11",
    namaBidangUrusan: "LINGKUNGAN HIDUP",
    kodeFungsi: "04",
    namaFungsi: "Perlindungan Lingkungan Hidup",
    kodeSubFungsi: "01",
    namaSubFungsi: "Pengendalian Pencemaran Lingkungan Hidup",
    kodeSkpd: "2.11.0.00.0.00.01.0000",
    namaSkpd: "Dinas Lingkungan Hidup",
    kodeSubSkpd: "2.11.0.00.0.00.01.0001",
    namaSubSkpd: "Sekretariat DLH Sumbawa Barat",
    kodeProgram: "2.11.01",
    namaProgram: "PROGRAM PENGURANGAN DAN PENANGANAN SAMPAH",
    kodeKegiatan: "2.11.01.2.02",
    namaKegiatan: "Pengadaan Sarana Prasarana Pengelolaan Sampah",
    kodeSubKegiatan: "2.11.01.2.02.05",
    namaSubKegiatan: "Penyediaan Tong Sampah dan Truk Arm Roll",
    kodeRekening: "5.2.02.05",
    namaRekening: "Belanja Modal Peralatan dan Mesin Alat Angkutan Darat Berorientasi Khusus",
    alokasiAnggaran: 4200000000,
    realisasiAnggaran: 2100000000
  }
];
